Try to address some of the build issues using a current proftpd version.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1256,6 +1256,12 @@ if test -n "$ac_init_help"; then
 
   cat <<\_ACEOF
 
+Optional Features:
+  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
+  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-devel          enable developer-only code (default=no)
+
+
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
@@ -1266,6 +1272,14 @@ Optional Packages:
   --with-libraries=LIST   add additional library paths to proftpd. LIST is a
                           colon-separated list of include paths to add e.g.
                           --with-libraries=/some/mysql/libdir:/my/libs
+
+  --with-modules=LIST     add additional modules to proftpd. LIST is a
+                          colon-separated list of modules to add e.g.
+                          --with-modules=mod_readme:mod_ifsession
+
+  --with-shared=LIST      build DSO modules for proftpd. LIST is a
+                          colon-separated list of modules to build as DSOs
+                          e.g. --with-shared=mod_rewrite:mod_ifsession
 
 
 Some influential environment variables:
@@ -4000,6 +4014,18 @@ fi
 done
 
 
+# Check whether --enable-devel was given.
+if test "${enable_devel+set}" = set; then
+  enableval=$enable_devel;
+    if test x"$enableval" != xno ; then
+      if test `echo $enableval | grep -c coverage` = "1" ; then
+        UTILS_LIBS="--coverage $UTILS_LIBS"
+      fi
+    fi
+
+fi
+
+
 
 # Check whether --with-includes was given.
 if test "${with_includes+set}" = set; then
@@ -4032,8 +4058,205 @@ if test "${with_libraries+set}" = set; then
 fi
 
 
+
+# Check whether --with-modules was given.
+if test "${with_modules+set}" = set; then
+  withval=$with_modules;
+    if test x"$withval" != x; then
+      if test x"$withval" = xyes; then
+        { { echo "$as_me:$LINENO: error: --with-modules parameter missing required colon-separated list of modules" >&5
+echo "$as_me: error: --with-modules parameter missing required colon-separated list of modules" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+
+      if test x"$withval" != xno; then
+        modules_list=`echo "$withval" | sed -e 's/:/ /g'`;
+
+        for amodule in $modules_list; do
+          if test x"$amodule" = xmod_sftp ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SFTP 1
+_ACEOF
+
+          fi
+        done
+      fi
+    fi
+
+fi
+
+
+
+# Check whether --with-shared was given.
+if test "${with_shared+set}" = set; then
+  withval=$with_shared;
+    if test x"$withval" != x; then
+      if test x"$withval" = xyes; then
+        { { echo "$as_me:$LINENO: error: --with-shared parameter missing required colon-separated list of modules" >&5
+echo "$as_me: error: --with-shared parameter missing required colon-separated list of modules" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+
+      if test x"$withval" != xno; then
+        shared_modules_list=`echo "$withval" | sed -e 's/:/ /g'`;
+
+        for amodule in $shared_modules_list; do
+          if test x"$amodule" = xmod_sftp ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SFTP 1
+_ACEOF
+
+          fi
+        done
+      fi
+    fi
+
+fi
+
+
+saved_libs="$LIBS"
+LIBS="$LIBS -lcrypto"
+
+{ echo "$as_me:$LINENO: checking whether linking with OpenSSL functions requires -ldl" >&5
+echo $ECHO_N "checking whether linking with OpenSSL functions requires -ldl... $ECHO_C" >&6; }
+saved_libs="$LIBS"
+
+LIBS=`echo "$LIBS" | sed -e 's/-lsupp//g'`;
+LIBS="-lcrypto -ldl $LIBS"
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #include <openssl/evp.h>
+
+int
+main ()
+{
+
+    SSLeay_add_all_algorithms();
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+    LIBS="$saved_libs -ldl"
+    UTILS_LIBS="$UTILS_LIBS -ldl"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    LIBS="$saved_libs"
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+{ echo "$as_me:$LINENO: checking whether linking with OpenSSL functions requires -lz" >&5
+echo $ECHO_N "checking whether linking with OpenSSL functions requires -lz... $ECHO_C" >&6; }
+saved_libs="$LIBS"
+
+LIBS=`echo "$LIBS" | sed -e 's/-lsupp//g'`;
+LIBS="-lcrypto -lz $LIBS"
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #include <openssl/evp.h>
+    #include <openssl/bio.h>
+    #include <openssl/comp.h>
+
+int
+main ()
+{
+
+    BIO *bio;
+    SSLeay_add_all_algorithms();
+    bio = BIO_new(BIO_f_zlib());
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+    LIBS="$saved_libs -lz"
+    UTILS_LIBS="$UTILS_LIBS -lz"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    LIBS="$saved_libs"
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+LIBS="$saved_libs"
 INCLUDES="$ac_build_addl_includes"
 LIBDIRS="$ac_build_addl_libdirs"
+
 
 
 
